# Generated by Django 5.2 on 2025-05-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('view_all_mailings', 'Может просматривать все рассылки'), ('disable_mailing', 'Может отключать рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'permissions': [('view_all_recipients', 'Может просматривать всех получателей'), ('block_recipient', 'Может блокировать получателей')], 'verbose_name': 'Получатель', 'verbose_name_plural': 'Получатели'},
        ),
    ]
