# Generated by Django 5.2 on 2025-04-19 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема сообщения')),
                ('body', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='body',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='subject',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(verbose_name='Дата и время окончания отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(verbose_name='Дата и время первой отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершена'), ('created', 'Создана'), ('running', 'Запущена')], default='created', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Сообщение'),
            preserve_default=False,
        ),
    ]
