# Generated by Django 5.2 on 2025-04-19 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_message_remove_mailing_body_remove_mailing_frequency_and_more'),
        ('postal_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postal_service.message', verbose_name='Сообщение'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
