# Generated by Django 5.2 on 2025-04-29 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_mailing_owner_recipient_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='last_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.recipient', verbose_name='Получатель'),
        ),
    ]
