# Generated by Django 5.2 on 2025-05-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postal_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('view_all_messages', 'Может просматривать все сообщения')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
